services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fusioncol-backend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Configurar aquí las variables de entorno de producción
      # - MONGODB_URI=mongodb+srv://user:pass@cluster.mongodb.net/fusioncol
      # - REDIS_URL=redis://user:pass@redis-host:6379
    restart: unless-stopped
    # Configuración para producción
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
